src/Entity/Classroom.php
<?php

namespace App\Entity;

use App\Repository\ClassroomRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClassroomRepository::class)
 */
class Classroom
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbr;

    /**
     * @ORM\OneToMany(targetEntity=Etudiant::class, mappedBy="classroom", cascade={"remove"})
     */
    private $etudiants;

    public function __toString()
    {
        return (string) $this->Name;
    }
    public function __construct()
    {
        $this->etudiants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getNbr(): ?int
    {
        return $this->nbr;
    }

    public function setNbr(?int $nbr): self
    {
        $this->nbr = $nbr;

        return $this;
    }

    /**
     * @return Collection|Etudiant[]
     */
    public function getEtudiants(): Collection
    {
        return $this->etudiants;
    }

    public function addEtudiant(Etudiant $etudiant): self
    {
        if (!$this->etudiants->contains($etudiant)) {
            $this->etudiants[] = $etudiant;
            $etudiant->setClassroom($this);
        }

        return $this;
    }

    public function removeEtudiant(Etudiant $etudiant): self
    {
        if ($this->etudiants->removeElement($etudiant)) {
            // set the owning side to null (unless already changed)
            if ($etudiant->getClassroom() === $this) {
                $etudiant->setClassroom(null);
            }
        }

        return $this;
    }

}

src/Entity/Etudiant.php
<?php

namespace App\Entity;

use App\Repository\EtudiantRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EtudiantRepository::class)
 */
class Etudiant
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    private $NCL;

    /**
     * @return mixed
     */
    public function getNCL()
    {
        return $this->NCL;
    }

    /**
     * @param mixed $NCL
     */
    public function setNCL($NCL): void
    {
        $this->NCL = $NCL;
    }

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\ManyToOne(targetEntity=Classroom::class, inversedBy="etudiants")
     * @ORM\JoinColumn(nullable=true)
     */
    private $classroom;


    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getClassroom(): ?Classroom
    {
        return $this->classroom;
    }

    public function setClassroom(?Classroom $classroom): self
    {
        $this->classroom = $classroom;

        return $this;
    }
}

src/Form/EtudiantType.php
<?php

namespace App\Form;

use App\Entity\Classroom;
use App\Entity\Etudiant;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtudiantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('NCL')
            ->add('Email',EmailType::class)
            //->add('classroom')
            ->add('classroom', EntityType::class, [

                'label' => 'classroom',
                'class' => Classroom::class,
            ])
           ->add('save',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Etudiant::class,
        ]);
    }
}

src/Controller/EtudiantController.php
<?php

namespace App\Controller;

use App\Entity\Etudiant;
use App\Entity\Student;
use App\Form\EtudiantType;
use App\Form\SearchStudentType;
use App\Repository\EtudiantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

use Symfony\Component\Routing\Annotation\Route;

class EtudiantController extends AbstractController
{
    /**
     * @Route("/etudiant", name="etudiant")
     */
    public function index(): Response
    {
        return $this->render('etudiant/index.html.twig', [
            'controller_name' => 'EtudiantController',
        ]);
    }

    /**
     * @Route("/affiche", name="affiche")
     */
    public function affiche(): Response
    {
        $Etudiant=$this->getDoctrine()->getRepository(Etudiant::class)->findAll();
        return $this->render('etudiant/afficheC.html.twig',['e'=>$Etudiant]);
    }

    /**
     * @Route("/Ajoute", name="Ajoute")
     */
    public function Ajoute(Request $request)
    {//récupération du formulaire
        $etudiant = new Etudiant();
        $form = $this->createForm(EtudiantType::class, $etudiant);
        /*Ajout du boutton dans l'action
        $form->add('Ajouter',SubmitType::class);*/
//récupérer les données saisies dans les champs
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($etudiant);
            $em->flush();
            return $this->redirectToRoute('affiche');
        }
        return $this->render("etudiant/Ajoute.html.twig",
            array('f'=>$form->createView()));
    }

    /**
     * @Route("/update/{ncl}", name="updateStudent")
     */
    public function update(Request $request, $ncl)
    {
        $student = $this->getDoctrine()->getRepository(Etudiant::class)->find($ncl);
        $form = $this->createForm(EtudiantType::class, $student);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute('affiche');
        }
        return $this->render("etudiant/update.html.twig", array('form' => $form->createView()));
    }

    /**
     * @Route("/supp/{ncl}", name="supprimer")
     */
    public function suppc($ncl): Response
    {  //recupere le classroom a supprime
        $student=$this->getDoctrine()->getRepository(Etudiant::class)->find($ncl);
        //on passe a la supppresion
        $em=$this->getDoctrine()->getManager();
        $em->remove($student);
        $em->flush();
        return $this->redirectToRoute('affiche');

    }
    /**
     * @Route("/listStudentWithSearch", name="listStudentWithSearch")
     */
    public function listStudentWithSearch(Request $request, EtudiantRepository $repository)
    {
//All of Student
        $students= $repository->findAll();
//list of students order By Mail
        $studentsByMail = $repository->orderByMail();
//search
        $searchForm = $this->createForm(SearchStudentType::class);
        $searchForm->add("Recherche",SubmitType::class);
        $searchForm->handleRequest($request);
        if ($searchForm->isSubmitted()) {
            $NCL = $searchForm['NCL']->getData();
            $resultOfSearch = $repository->searchStudent($NCL);
            return $this->render('etudiant/searchStudent.html.twig', array(
                "resultOfSearch" => $resultOfSearch,
                "searchStudent" => $searchForm->createView()));
        }
        return $this->render('etudiant/listWithSearch.html.twig', array(
            "students" => $students,
            "studentsByMail" => $studentsByMail,
            "searchStudent" => $searchForm->createView()));
    }
}

templates/etudiant/Ajoute.html.twig
<h2>Ajoutc</h2>
{{ form(f) }}

templates/etudiant/afficheC.html.twig
<h2>Etudiant</h2>
<table border="5">
<tr>
    <td>NCL</td>
    <td>EMAIL</td>
    <td>classroom</td>
</tr>
    {% for a in e %}
    <tr>
        <td>{{ a.ncl}}</td>
        <td>{{ a.Email }}</td>
       <td>{{ a.classroom.Name }}</td>



        <td>
   <form action="{{ path('supprimer',{'ncl':a.ncl}) }}">
            <button>supprime</button>
        </form>
        </td>
        <td>
            <form action="{{ path('updateStudent',{'ncl':a.ncl}) }}">
                <button>Modifier</button>
          </form>
        </td>
    </tr>
    {% endfor %}
</table>

templates/etudiant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EtudiantController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/FirstProject/src/Controller/EtudiantController.php'|file_link(0) }}">src/Controller/EtudiantController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/FirstProject/templates/etudiant/index.html.twig'|file_link(0) }}">templates/etudiant/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/etudiant/listWithSearch.html.twig
{{ form(searchStudent) }}
<table border="1">
    <tr>
        <td>NSC</td>
        <td>Email</td>
        <td>Classe</td>
        <td>Action</td>
    </tr>
    {% for student in students %}
        <tr>
            <td>{{ student.ncl }}</td>
            <td>{{ student.Email }}</td>
            <td>{{ student.classroom.Name }}</td>

        </tr>
    {% endfor %}
</table>
<h1>List of students order By Mail</h1>
<table border="1">
    <tr>
        <td>NSC</td>
        <td>Email</td>
        <td>Classe</td>
        <td>Action</td>
    </tr>
    {% for student in studentsByMail %}
        <tr>
            <td>{{ student.ncl }}</td>
            <td>{{ student.Email }}</td>
            <td>{{ student.classroom.Name }}</td>
        </tr> {% endfor %}
</table>

templates/etudiant/searchStudent.html.twig
{{ form(searchStudent) }}
<table border="1">
    <tr>
        <td>NSC</td>
        <td>Email</td>
        <td>Classe</td>
        <td>Action</td>
    </tr>
    {% for student in resultOfSearch %}
        <tr>
            <td>{{ student.NCL }}</td>
            <td>{{ student.email }}</td>
            <td>{{ student.classroom.name }}</td>
        </tr>
    {% endfor %}
</table>

templates/etudiant/update.html.twig
<h2>Update</h2>
{{ form(form) }}